name: Jazzy Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.0"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Jazzy
        run: gem install jazzy
      - name: Run Jazzy
        run: jazzy
      - name: Deploy
        run: |
          cd docs
          git init
          git config user.name  "CI"
          git config user.email "jazzy-ci@github.com"
          git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/zonble/CurlDSL.git
          git checkout -b gh-pages
          git add .
          git commit -m "Updated docs"
          git push --force secure-origin gh-pages
